Testing
a99jafari/todo-application pull request #2
Opened 2020-12-03 07:45 UTC by a99jafari

2020-12-03 08:48 UTC, sassanh commented on src/components/Filter/index.spec.tsx
> +    it("Calling callback one time exactly in each click", () => {
There is a reason this function is named `it`: it is supposed to be the first word in an English sentence starting with "it", each test description should be an English sentence starting with "it"
```suggestion
    it('calls callback "onFilter" whenever it is activated by clicking on the element with "button" role', () => {
```
Please fix other tests descriptions too

2020-12-03 08:52 UTC, a99jafari commented on src/components/Filter/index.spec.tsx
> +    it("Calling callback one time exactly in each click", () => {
Awesome! Thank you

2020-12-07 13:28 UTC, ArsalanGh1996 requested changes

2020-12-07 13:28 UTC, ArsalanGh1996 commented on src/components/Filter/index.spec.tsx
> +    it("matches snapshots.", () => {
it('matches the snapshot') 
here we have only one snapshot

2020-12-07 13:28 UTC, ArsalanGh1996 commented on src/components/Filter/index.spec.tsx
> +        const randomTitle = lorem.word();
most of the times we don't use "random" or "mocked" for the arbitrary texts or numbers etc, 
because when we are in the testing environment we know that all of these entities are random

2020-12-07 13:49 UTC, a99jafari commented on src/components/AddTodo/index.spec.tsx
> +import { render, fireEvent } from "@testing-library/react";
These empty spaces added automatically by code formatter (extension name's is "Prettier") in VSCode. I will change it's config to fix it.

2020-12-07 14:03 UTC, a99jafari commented on src/components/Filter/index.spec.tsx
> +        const randomTitle = lorem.word();
lorem.word() is a method of "faker" library and return a random word.

2020-12-07 14:07 UTC, a99jafari commented on src/components/AddTodo/index.spec.tsx
> +
Also this issue is related to the "Prettier" extension. I will fix it.

2020-12-07 14:28 UTC, a99jafari commented on src/components/Filter/index.spec.tsx
> +    it("matches snapshots.", () => {
Thank you

2020-12-07 14:30 UTC, a99jafari commented on src/components/AddTodo/index.spec.tsx
> +        clicking on the element with "button" role`, () => {
Thanks a lot Arsalan

2020-12-07 14:42 UTC, ArsalanGh1996 commented on src/components/AddTodo/index.spec.tsx
> +import { render, fireEvent } from "@testing-library/react";
Yes you should disable prettier but it  is not necessary now because
when you start working on code-base some rules of our eslint automatically prevent you from adding these spaces, but I just told you to be familiar with the idea

2020-12-07 14:42 UTC, ArsalanGh1996 commented on src/components/AddTodo/index.spec.tsx
> +
Actually I just told you some of our eslint rules

2020-12-07 14:42 UTC, ArsalanGh1996 commented on src/components/Filter/index.spec.tsx
> +        const randomTitle = lorem.word();
yes,but the name of the variable was my point 
I meant you shouldn't name your variables as RandomThing or MockedThing

2020-12-07 14:45 UTC, ArsalanGh1996 commented on src/components/AddTodo/index.spec.tsx
> +import React from "react";
which you have it here :) so ignore it

2020-12-08 08:18 UTC, ArsalanGh1996 commented on src/components/AddTodo/index.spec.tsx
> +        in textbox, when clicked on the element with "button" role.', () => {
you can make it more simple like:
it('calls the provided "onAdd" callback with the entered text \
in textbox, when the button is clicked.')

2020-12-08 08:18 UTC, ArsalanGh1996 commented on src/components/AddTodo/index.spec.tsx
> +        in textbox, when clicked on the element with "button" role.', () => {
but it's ok :+1:

2020-12-08 08:18 UTC, ArsalanGh1996 commented on src/components/Todos/index.spec.tsx
> +                title: random.words(random.number({ min: 1, max: 10 })),
nice we use random.word() or words() or uuid() alot

2020-12-08 08:18 UTC, ArsalanGh1996 commented on src/components/Filters/index.spec.tsx
> -        const randomFilterItem = random.arrayElement(randomFilterItems);
:+1:

2020-12-08 08:18 UTC, ArsalanGh1996 commented on src/components/Filters/index.spec.tsx
> +        const filterItems = [...Array(filterSize)].map(() => lorem.word());
sometimes you can save some lines by doing this 
filterItems = [...Array(random.number({ min: 1, max: 10 }))].map(() => lorem.word());
and delete the const filterSize part
but make sure that the code does not get so complicated

2020-12-08 09:20 UTC, ArsalanGh1996 commented on src/components/Todo/index.spec.tsx
> +    it('calls the "onReomve" callback when it is activated by clicking on the element with "button" role', () => {
you can be more specific here because here the user should click on the "Remove button" or any button which is for the deleting

2020-12-08 09:20 UTC, ArsalanGh1996 commented on src/components/Todo/index.spec.tsx
> +        const {asFragment} = render(<Todo todo={todoItem} onRemove={() => {}} onComplete={() => {}} />);
Also check that onRemove is getting called with the correct argument which is a "todo" if I'm correct

2020-12-08 09:23 UTC, ArsalanGh1996 commented on src/components/Todo/index.spec.tsx
> +    it('calls the "onReomve" callback when it is activated by clicking on the element with "button" role', () => {
think of the situation when the component has 2 or more buttons

2020-12-08 11:41 UTC, ArsalanGh1996 approved these changes

2020-12-08 11:41 UTC, ArsalanGh1996 commented on src/components/Todo/index.spec.tsx
> +    it('calls the "onReomve" callback with the todo prop as the argument by clicking on the remove button.', () => {
we should refer to "Things" which are provided by the props with "provided Things" or "given Tings"

2020-12-08 12:03 UTC, merged

2020-12-08 12:06 UTC, a99jafari commented on src/components/Todo/index.spec.tsx
> +    it('calls the "onReomve" callback with the todo prop as the argument by clicking on the remove button.', () => {
Good point. Thank you Arsalan for your attention to the details. I will change it.